package com.luoshengwei.ssm.test.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.luoshengwei.common.core.dao.BaseDao;
import com.luoshengwei.ssm.test.annotation.MybatisRepository;
import com.luoshengwei.ssm.test.entity.ItBsEmployeeInformation;
import com.luoshengwei.ssm.test.entity.ItBsEmployeeInformationExample;

@MybatisRepository
public interface ItBsEmployeeInformationDAO extends BaseDao<ItBsEmployeeInformation>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int countByExample(ItBsEmployeeInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int deleteByExample(ItBsEmployeeInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    long insert(ItBsEmployeeInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int insertSelective(ItBsEmployeeInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    List<ItBsEmployeeInformation> selectByExample(ItBsEmployeeInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    ItBsEmployeeInformation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") ItBsEmployeeInformation record, @Param("example") ItBsEmployeeInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int updateByExample(@Param("record") ItBsEmployeeInformation record, @Param("example") ItBsEmployeeInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int updateByPrimaryKeySelective(ItBsEmployeeInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IT_BS_EMPLOYEE_INFORMATION
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    int updateByPrimaryKey(ItBsEmployeeInformation record);
}