package com.luoshengwei.ssm.test.dao;

import java.sql.SQLException;
import java.util.List;

import com.luoshengwei.common.core.dao.BaseDao;
import com.luoshengwei.ssm.test.entity.ItSmUser;
import com.luoshengwei.ssm.test.entity.ItSmUserExample;

/**
 * @ClassName:ItSmUserDAO
 * @Description:(系统管理-用户管理-数据访问层接口)
 * @author:luoshengwei
 * @date:2018-4-6 下午4:55:24
 * @Copyright: 2018 luoshengwei All rights reserved.
 */
public interface ItSmUserDAO extends BaseDao<ItSmUser> {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	int countByExample(ItSmUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	int deleteByExample(ItSmUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	int deleteByPrimaryKey(String id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	long insert(ItSmUser record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	void insertSelective(ItSmUser record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	List selectByExample(ItSmUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	ItSmUser selectByPrimaryKey(String id) throws SQLException;
	
	ItSmUser selectByNameAndPassword(ItSmUser record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	int updateByExampleSelective(ItSmUser record, ItSmUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	int updateByExample(ItSmUser record, ItSmUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	int updateByPrimaryKeySelective(ItSmUser record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table IT_SM_USER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	int updateByPrimaryKey(ItSmUser record) throws SQLException;
}