package com.luoshengwei.ssm.test.entity;

import java.io.Serializable;

import com.luoshengwei.common.core.entity.BaseEntity;

/**
 * @ClassName:ItBsEmployeeInformation
 * @Description:(系统管理-员工信息管理-实体类)
 * @author:luoshengwei
 * @date:2018-4-6 下午4:56:03
 * @Copyright: 2018 luoshengwei All rights reserved.
 */
public class ItBsEmployeeInformation extends BaseEntity implements Serializable {
    /**
	 * Comment for <code>serialVersionUID</code>
	 */
	private static final long serialVersionUID = -3460280994981481674L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IT_BS_EMPLOYEE_INFORMATION.ID
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IT_BS_EMPLOYEE_INFORMATION.NAME
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IT_BS_EMPLOYEE_INFORMATION.CODE
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IT_BS_EMPLOYEE_INFORMATION.SEX
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IT_BS_EMPLOYEE_INFORMATION.DEPARTMENT
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IT_BS_EMPLOYEE_INFORMATION.ID
     *
     * @return the value of IT_BS_EMPLOYEE_INFORMATION.ID
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IT_BS_EMPLOYEE_INFORMATION.ID
     *
     * @param id the value for IT_BS_EMPLOYEE_INFORMATION.ID
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IT_BS_EMPLOYEE_INFORMATION.NAME
     *
     * @return the value of IT_BS_EMPLOYEE_INFORMATION.NAME
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IT_BS_EMPLOYEE_INFORMATION.NAME
     *
     * @param name the value for IT_BS_EMPLOYEE_INFORMATION.NAME
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IT_BS_EMPLOYEE_INFORMATION.CODE
     *
     * @return the value of IT_BS_EMPLOYEE_INFORMATION.CODE
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IT_BS_EMPLOYEE_INFORMATION.CODE
     *
     * @param code the value for IT_BS_EMPLOYEE_INFORMATION.CODE
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IT_BS_EMPLOYEE_INFORMATION.SEX
     *
     * @return the value of IT_BS_EMPLOYEE_INFORMATION.SEX
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IT_BS_EMPLOYEE_INFORMATION.SEX
     *
     * @param sex the value for IT_BS_EMPLOYEE_INFORMATION.SEX
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IT_BS_EMPLOYEE_INFORMATION.DEPARTMENT
     *
     * @return the value of IT_BS_EMPLOYEE_INFORMATION.DEPARTMENT
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IT_BS_EMPLOYEE_INFORMATION.DEPARTMENT
     *
     * @param department the value for IT_BS_EMPLOYEE_INFORMATION.DEPARTMENT
     *
     * @mbggenerated Sat Jan 06 21:52:09 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}