package com.luoshengwei.ssm.test.entity;

import java.io.Serializable;
import java.util.Date;

import com.luoshengwei.common.core.entity.BaseEntity;

/**
 * @ClassName:ItSmUser
 * @Description:(系统管理-用户管理-实体类)
 * @author:luoshengwei
 * @date:2018-4-6 下午4:56:48
 * @Copyright: 2018 luoshengwei All rights reserved.
 */
public class ItSmUser extends BaseEntity implements Serializable {

	/**
	 * Comment for <code>serialVersionUID</code>
	 */
	private static final long serialVersionUID = -3317910151765820481L;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.ID
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.CODE
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.NAME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.PASSWORD
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.TYPE
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private String type;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.CREATETIME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.CREATEUSER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private String createuser;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.MODIFYTIME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private Date modifytime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column IT_SM_USER.MODIFYUSER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	private String modifyuser;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.ID
	 * @return  the value of IT_SM_USER.ID
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.ID
	 * @param id  the value for IT_SM_USER.ID
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.CODE
	 * @return  the value of IT_SM_USER.CODE
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.CODE
	 * @param code  the value for IT_SM_USER.CODE
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.NAME
	 * @return  the value of IT_SM_USER.NAME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.NAME
	 * @param name  the value for IT_SM_USER.NAME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.PASSWORD
	 * @return  the value of IT_SM_USER.PASSWORD
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.PASSWORD
	 * @param password  the value for IT_SM_USER.PASSWORD
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.TYPE
	 * @return  the value of IT_SM_USER.TYPE
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.TYPE
	 * @param type  the value for IT_SM_USER.TYPE
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.CREATETIME
	 * @return  the value of IT_SM_USER.CREATETIME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.CREATETIME
	 * @param createtime  the value for IT_SM_USER.CREATETIME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.CREATEUSER
	 * @return  the value of IT_SM_USER.CREATEUSER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public String getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.CREATEUSER
	 * @param createuser  the value for IT_SM_USER.CREATEUSER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.MODIFYTIME
	 * @return  the value of IT_SM_USER.MODIFYTIME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public Date getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.MODIFYTIME
	 * @param modifytime  the value for IT_SM_USER.MODIFYTIME
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column IT_SM_USER.MODIFYUSER
	 * @return  the value of IT_SM_USER.MODIFYUSER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public String getModifyuser() {
		return modifyuser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column IT_SM_USER.MODIFYUSER
	 * @param modifyuser  the value for IT_SM_USER.MODIFYUSER
	 * @ibatorgenerated  Sat Jan 06 00:19:15 CST 2018
	 */
	public void setModifyuser(String modifyuser) {
		this.modifyuser = modifyuser;
	}
}